CREATE TABLE Users (
  userID INT PRIMARY KEY IDENTITY,
  username NVARCHAR(50) NOT NULL,
  email NVARCHAR(100) NOT NULL UNIQUE,
  password NVARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT GETDATE()
);


CREATE TABLE Posts (
  postID INT PRIMARY KEY IDENTITY(1,1),
  title NVARCHAR(255) NOT NULL,
  content NVARCHAR(MAX) NOT NULL,
  authorID INT NOT NULL,
  created_at DATETIME DEFAULT GETDATE(),
  imageUrl NVARCHAR(255) NULL
);



CREATE TABLE Comments (
  commentID INT PRIMARY KEY IDENTITY,
  postID INT,
  userID INT,
  content TEXT,
  created_at DATETIME DEFAULT GETDATE(),
  FOREIGN KEY (postID) REFERENCES BlogPosts(postID),
  FOREIGN KEY (userID) REFERENCES Users(userID)
);
